version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'tthd-app.work -> http://node:3000, live.tthd-app.work -> http://livego:7001'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
      STAGE: local
    volumes: 
      - https-portal-data:/var/lib/https-portal
  node:
    build: 
      context: .
      dockerfile: ./Dockerfile.node.dev
    tty: true
    volumes:
      - ./app:/app
    restart: always
    ports:
      - "3000:3000"
  livego:
    image: gwuhaolin/livego
    tty: true
    restart: always
    ports:
      - "0.0.0.0:1935:1935"
      - "0.0.0.0:7001:7001"
      - "0.0.0.0:7002:7002"
      - "0.0.0.0:8090:8090"

volumes:
  https-portal-data:
